version: 2
jobs:
  build:
    docker:
    - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
    - HUGO_BUILD_DIR: ~/hugo/public
    steps:
    - run: sudo apt-get update -y && sudo apt-get install git curl unzip -y
    - checkout
    - run: git submodule sync && git submodule update --init
    - run:
        name: install AWS CLI
        command: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
    - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
    - deploy:
        name: deploy to AWS
        command: |-
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            aws s3 sync $HUGO_BUILD_DIR \
            s3://devopswelldoitlive/ --delete
          else
            echo "Not master branch, dry run only"
          fi
workflows:
  version: 2
  workflow:
    jobs:
    - build
